In [33]:
#All imports
import numpy as np
import pandas as pd
#dataset imports to initialize model and test it and migrate to new data
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
#Train and test split auto framework
from sklearn.model_selection import train_test_split
#score and other mmetrics 
from sklearn.metrics import accuracy_score, classification_report
import yfinance as yf

In [34]:
#Load iris data for quick model building and testing
iris = load_iris()
x = iris.data
y = (iris.target == 2).astype(int)

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
print(x_train)
print(y_train)

[[4.6 3.6 1.  0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.3 2.5 5.  1.9]
 [6.4 3.2 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.

In [42]:
#Data will be with YF
#We need to categorize data as on x price data for example
#apple data from 22 to 24
data =  yf.download("BTC-USD", start="2022-01-01", end="2025-10-01")

#creating features
data["Return"] = data['Close'].pct_change()
data["MA5"] = data['Close'].rolling(window=5).mean()
data["MA10"] = data['Close'].rolling(window=10).mean()

#print(data)

#drop NAN values don't make an influence on our descision and random noise
data = data.dropna()
print(data)




C:\Users\shaik\AppData\Local\Temp\ipykernel_64688\2437134855.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data =  yf.download("BTC-USD", start="2022-01-01", end="2025-10-01")
[*********************100%***********************]  1 of 1 completed

Price               Close           High            Low           Open  \
Ticker            BTC-USD        BTC-USD        BTC-USD        BTC-USD   
Date                                                                     
2022-01-10   41821.261719   42199.484375   39796.570312   41910.230469   
2022-01-11   42735.855469   43001.156250   41407.753906   41819.507812   
2022-01-12   43949.101562   44135.367188   42528.988281   42742.179688   
2022-01-13   42591.570312   44278.421875   42447.042969   43946.742188   
2022-01-14   43099.699219   43346.687500   41982.617188   42598.871094   
...                   ...            ...            ...            ...   
2025-09-26  109712.828125  110359.195312  108728.976562  109041.296875   
2025-09-27  109681.945312  109778.500000  109144.296875  109707.140625   
2025-09-28  112122.640625  112375.484375  109236.945312  109681.945312   
2025-09-29  114400.382812  114473.570312  111589.953125  112117.875000   
2025-09-30  114056.085938  114836.6171

In [43]:
# create target: 1 if tomorrow's close > today's, else 0
data["Target"] = np.where(data['Close'].shift(-1) > data['Close'], 1,0)
x = data[["Return", "MA5", "MA10"]]
y = data["Target"]

#train and test split 
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1,shuffle=False)

In [44]:
#building model
model = LogisticRegression()
model.fit(x_train, y_train)


LogisticRegression()

In [45]:
#Prediction
print(x_train)
y_pred = model.predict(x_test)
print(y_pred)

Price         Return            MA5           MA10
Ticker                                            
Date                                              
2022-01-10 -0.002155   42037.127344   44114.236328
2022-01-11  0.021869   41952.112500   43619.140625
2022-01-12  0.028389   42430.352344   43279.528906
2022-01-13 -0.030889   42601.878125   42892.874219
2022-01-14  0.011930   42839.497656   42613.086719
...              ...            ...            ...
2025-05-13  0.013197  103751.260938  100489.659375
2025-05-14 -0.006052  103864.973437  101412.003125
2025-05-15  0.001982  103674.635938  102311.661719
2025-05-16 -0.002461  103551.221875  102980.342969
2025-05-17 -0.002881  103626.848437  103596.219531

[1224 rows x 3 columns]
[1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1

In [46]:
y_pred = model.predict(x_test)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("\nClassification report:\n", classification_report(y_test,y_pred))

Accuracy:  0.5

Classification report:
               precision    recall  f1-score   support

           0       0.50      0.25      0.33        68
           1       0.50      0.75      0.60        68

    accuracy                           0.50       136
   macro avg       0.50      0.50      0.47       136
weighted avg       0.50      0.50      0.47       136



In [47]:
#Next day prediction
latest = x.iloc[-1].values.reshape(1, -1)
next_day_prediction = model.predict(latest)
print("Prediction for next day:", "UP" if next_day_prediction[0] == 1 else "DOWN")

Prediction for next day: UP
